image: node:22

stages:
  - install
  - lint
  - prettier
  - build

install:
  stage: install
  script:
    - npm ci --legacy-peer-deps
  artifacts:
    paths:
      - node_modules/

lint:
  stage: lint
  script:
    - npm run lint
  dependencies:
    - install

prettier:
  stage: prettier
  script:
    - npm run prettier:fix
  dependencies:
    - install

build:
  stage: build
  script:
    - npm run build
  dependencies:
    - install
